const Equipos = [
    {
        name: "Arsenal",
        contry: "England",
        memberNumber: "23",
        coach: "Mikel Arteta",
        goalkeepers: ["David Raya", "Neto", "Tommy Setford", "Alexei Rojas Fedorushchenko", "Jack Porter"],
        defenses: ["William Saliba", "Ben White", "Jurriën Timber", "Oleksandr Zinchenko", "Riccardo Calafiori", "Josh Nichols", "Ayden Heaven", "Kieran Tierney", "Gabriel Magalhães", "Jakub Kiwior", "Takehiro Tomiyasu", "Maldini Kacurri", "Josh Robinson"],
        midfielders: ["Thomas Partey", "Jorginho", "Myles Lewis-Skelly", "Salah-Eddine Oulad M'hand", "Martin Ødegaard", "Mikel Merino", "Declan Rice", "Ethan Nwaneri"],
        fronts: ["Bukayo Saka", "Gabriel Martinelli", "Raheem Sterling", "Ismeal Kabia", "Gabriel Jesus", "Leandro Trossard", "Nathan Butler-Oyedeji"],                                                                                  
    },
    {
        name: "Aston Villa",
        contry: "England",
        memberNumber: "35",
        coach: "Unai Emery",
        goalkeepers: ["Joe Gauci", "Emiliano Martínez", "Robin Olsen", "Oliwier Zych"],
        defenses: ["Tyrone Mings", "Diego Carlos", "Lucas Digne", "Kosta Nedeljkovic", "Lamare Bogarde", "Triston Rowe", "Thierry Katsukunya", "Matty Cash", "Ezri Konsa", "Pau Torres", "Ian Maatsen", "Kortney Hause", "Sil Swinkels"],                                 
        midfielders: ["Ross Barkley","Youri Tielemans", "Amadou Onana", "Jacob Ramsey", "Aidan Borland", "Travis Patterson", "John McGinn", "Emiliano Buendía", "Leon Bailey", "Boubacar Kamara", "Jamaldeen Jimoh", "Ben Broggio"],
        fronts: ["Jhon Durán", "Jaden Philogene", "Kadan Young", "Ollie Watkins", "Morgan Rogers", "Kobei Moore"],                                                                                  
    },
    {
        name: "Atalanta",
        contry: "Italy",
        memberNumber: "32",
        coach: "Gian Piero Gasperini",
        goalkeepers: ["Rui Patrício", "Francesco Rossi", "Marco Carnesecchi"],
        defenses: ["Rafael Tolói", "Isak Hien", "Berat Djimsiti", "Pietro Comi", "Giorgio Scalvini", "Tommaso Del Lungo", "Odilon Kossounou", "Ben Godfrey", "Sead Kolasinac", "Pietro Tornaghi", "Lorenzo Bernasconi", "Brandon Soppy"],                                 
        midfielders: ["Ibrahim Sulemana", "Mario Pasalic", "Marten de Roon", "Matteo Ruggeri", "Federico Cassa", "Lorenzo Riccio", "Dominic Vavassori", "Davide Zappacosta", "Juan Cuadrado", "Éderson", "Raoul Bellanova", "Lazar Samardzic", "Marco Palestra", "Marco Brescianini", "Alberto Manzoni"],
        fronts: ["Gianluca Scamacca", "Ademola Lookman", "Mateo Retegui", "Nicolò Zaniolo", "Charles De Ketelaere", "Vanja Vlahovic"],                                                                                  
    },
    {
        name: "Atlético de Madrid",
        contry: "Spain",
        memberNumber: "35",
        coach: "Diego Simeone",
        goalkeepers: ["Juan Musso","Antonio Gomis", "Jan Oblak", "Alejandro Iturbe"],
        defenses: ["José Giménez", "Clément Lenglet", "Axel Witsel", "Reinildo", "Ilias Kostis", "Gerónimo Spina", "César Azpilicueta", "Nahuel Molina", "Javi Galán", "Robin Le Normand", "Carlos Giménez"],                                 
        midfielders: ["Conor Gallagher", "Koke", "Thomas Lemar", "Marcos Llorente", "Javi Serrano", "Rodrigo De Paul", "Pablo Barrios", "Samuel Lino", "Rodrigo Riquelme", "Jano Monserrate"],
        fronts: ["Antoine Griezmann", "Ángel Correa", "Giuliano Simeone", "Alexander Sørloth", "Julián Alvarez"],                                                                                  
    },
    {
        name: "Barcelona",
        contry: "Spain",
        memberNumber: "38",
        coach: "Hans-Dieter Flick",
        goalkeepers: ["Wojciech Szczesny", "Iñaki Peña", "Diego Kochen", "Marc-André ter Stegen", "Ander Astralaga", "Áron Yaakobishvili"],
        defenses: ["Pau Cubarsí", "Ronald Araujo", "Andreas Christensen", "Eric García", "Gerard Martín", "Andrés Cuenca", "Alejandro Balde", "Iñigo Martínez", "Jules Koundé", "Héctor Fort", "Sergi Domínguez"],                                 
        midfielders: ["Gavi","Pablo Torre", "Marc Casadó", "Frenkie de Jong", "Guille Fernández", "Pedri", "Fermín López", "Dani Olmo", "Marc Bernal"],
        fronts: ["Ferran Torres", "Ansu Fati", "Pau Víctor", "Toni Fernández", "Robert Lewandowski", "Raphinha", "Lamine Yamal"],                                                                                  
    },
    {
        name: "Bayer Leverkusen",
        contry: "Germany",
        memberNumber: "32",
        coach: "Xabi Alonso",
        goalkeepers: ["Lukás Hrádecky", "Niklas Lomb", "Matej Kovár"],
        defenses: ["Piero Hincapié", "Edmond Tapsoba", "Álex Grimaldo", "Jeremie Frimpong", "Jonathan Tah", "Arthur", "Nordi Mukiele", "Jeanuël Belocian"],                                 
        midfielders: ["Jonas Hofmann", "Florian Wirtz", "Aleix García", "Othniël Raterink","Sadik Fofana", "Robert Andrich", "Nathan Tella", "Exequiel Palacios", "Granit Xhaka"],
        fronts: ["Martin Terrier", "Amine Adli", "Artem Stepanov", "Patrik Schick", "Victor Boniface", "Francis Onyeka"],                                                                                  
    },
    {
        name: "Benfica",
        contry: "Portugal",
        memberNumber: "34",
        coach: "Bruno Miguel Silva do Nascimento",
        goalkeepers: ["Anatolii Trubin", "André Gomes", "Samuel Soares"],
        defenses: ["Álvaro Carreras", "Alexander Bah", "Nicolás Otamendi", "Tomás Araújo", "António Silva", "Issa Kaboré", "Jan-Niklas Beste", "Adrian Bajrami"],                                 
        midfielders: ["Fredrik Aursnes", "Ángel Di María", "Florentino", "Renato Sanches", "Orkun Kökçü", "Leandro Barreiro", "João Rêgo"],
        fronts: ["Zeki Amdouni", "Vangelis Pavlidis", "Andreas Schjelderup", "Benjamín Rollheiser", "Arthur Cabral", "Kerem Aktürkoglu", "Gianluca Prestianni", "Tiago Gouveia"],                                                                                  
    },
    {
        name: "Bologna",
        contry: "Italy",
        memberNumber: "35",
        coach: "Vincenzo Italiano",
        goalkeepers: ["Lukasz Skorupski", "Nicola Bagnolini", "Federico Ravaglia"],
        defenses: ["Emil Holm", "Martin Erlic", "Tommaso Corazza", "Jhon Lucumí", "Sam Beukema", "Stefan Posch", "Nicolò Casale", "Charalampos Lykogiannis", "Lorenzo De Silvestri", "Juan Miranda"],                                 
        midfielders: ["Nikola Moro", "Oussama El Azzouzi", "Lewis Ferguson", "Giovanni Fabbian", "Remo Freuler", "Tommaso Pobega", "Michel Aebischer", "Kacper Urbanski"],
        fronts: ["Riccardo Orsolini", "Jesper Karlsson", "Samuel Iling-Junior", "Thijs Dallinga", "Benjamín Domínguez", "Santiago Castro", "Dan Ndoye", "Jens Odgaard", "Nicolò Cambiaghi"],                                                                                  
    },
    {
        name: "Borussia Dortmund",
        contry: "Germany",
        memberNumber: "38",
        coach: "Nuri Sahin",
        goalkeepers: ["Gregor Kobel", "Alexander Meyer", "Silas Ostrzinski", "Marcel Lotka"],
        defenses: ["Yan Couto", "Nico Schlotterbeck", "Niklas Süle", "Filippo Mané", "Waldemar Anton", "Ramy Bensebaini", "Julian Ryerson","Almugera Kabar"],                                 
        midfielders: ["Giovanni Reyna", "Julian Brandt", "Marcel Sabitzer", "Kjell-Arik Wätjen", "Felix Nmecha", "Pascal Groß", "Emre Can", "Ayman Azhil"],
        fronts: ["Serhou Guirassy", "Julien Duranville", "Karim Adeyemi", "Jamie Gittens", "Maximilian Beier", "Donyell Malen", "Cole Campbell"],                                                                                  
    },
    {
        name: "Stade Brestois 29",
        contry: "France",
        memberNumber: "35",
        coach: "Éric Roy",
        goalkeepers: ["Grégoire Coudert", "Noah Jauny", "Marco Bizot"],
        defenses: ["Bradley Locko", "Brendan Chardonnet", "Kenny Lala", "Massadio Haïdara", "Julien Le Cardinal", "Abdoulaye Ndiaye", "Edimilson Fernandes", "Luck Zogbé", "Jordan Amavi", "Soumaïla Coulibaly"],                                 
        midfielders: ["Hugo Magnetti", "Romain Del Castillo", "Pierre Lees-Melou", "Mathias Pereira Lage", "Mahdi Camara", "Kamory Doumbia", "Axel Camblan","Romain Faivre", "Jonas Martin"],
        fronts: ["Léo Botz", "Abdallah Sima", "Ibrahim Kanté", "Ibrahim Salah", "Mama Baldé", "Ludovic Ajorque", "Serigne Diop"],                                                                                  
    },
    {
        name: "Celtic",
        contry: "Scotland",
        memberNumber: "41",
        coach: "Brendan Rodgers",
        goalkeepers: ["Kasper Schmeichel", "Scott Bain", "Viljami Sinisalo"],
        defenses: ["Alistair Johnston", "Liam Scales", "Álex Valle", "Cameron Carter-Vickers", "Anthony Ralston", "Colby Donovan","Greg Taylor", "Auston Trusty", "Maik Nawrocki", "Adam Montgomery", "Stephen Welsh"],                                 
        midfielders: ["Luke McCowan", "Arne Engels", "Reo Hatate", "James Forrest", "Odin Holm", "Paulo Bernardo", "Callum McGregor", "Francis Turley"],
        fronts: ["Luis Palma", "Adam Idah", "Yang Hyun-Jun", "Kyogo Furuhashi", "Nicolas Kühn", "Daizen Maeda"],                                                                                  
    },
    {
        name: "Club Brugge",
        contry: "Belgium",
        memberNumber: "33",
        coach: "Nicky Hayen",
        goalkeepers: ["Dani van den Heuvel", "Nordin Jackers", "Simon Mignolet", "Axl de Corte"],
        defenses: ["Zaid Romero", "Bjorn Meijer", "Hugo Siquet", "Maxim De Cuyper", "Kyriani Sabbe", "Joel Ordóñez", "Dedryck Boyata", "Brandon Mechele", "Jorne Spileers", "Joaquin Seys"],                                 
        midfielders: ["Hugo Vetlesen", "Hans Vanaken", "Ardon Jashari", "Casper Nielsen", "Lynnt Audoor"],
        fronts: ["Andreas Skov Olsen", "Ferran Jutglà", "Gustaf Nilsson", "Chemsdine Talbi", "Christos Tzolis", "Romeo Vermant", "Michal Skóras"],                                                                                  
    },
    {
        name: "Estrella Roja",
        contry: "Serbia",
        memberNumber: "36",
        coach: "Vladan Milojevic",
        goalkeepers: ["Marko Ilic", "Ivan Gutesa", "Omri Glazer"],
        defenses: ["Milos Degenek", "Milan Rodic", "Stefan Lekovic", "Veljko Milosavljevic", "Ognjen Mimovic", "Uros Spajic", "Nasser Djiga", "Vanja Drkusic", "Seol Young-Woo"],                                 
        midfielders: ["Mirko Ivanic", "Jovan Sljivic", "Aleksandar Katai", "Dálcio", "Andrija Maksimovic", "Rade Krunic", "Guélor Kanga", "Timi Elsnik", "Luka Ilic", "Egor Prutsev"],
        fronts: ["Cherif Ndiaye", "Silas Katompa Mvumpa", "Milson", "Vladimir Lucic", "Lazar Jovanovic", "Peter Olayinka", "Bruno Duarte", "Uros Sremcevic", "Nemanja Radonjic"],                                                                                  
    },
    {
        name: "Dinamo Zagerb",
        contry: "Croatia",
        memberNumber: "39",
        coach: "Nenad Bjelica",
        goalkeepers: ["Danijel Zagorac", "Ivan Filipovic", "Ivan Nevistic"],
        defenses: ["Sadegh Moharrami", "Raúl Torrente", "Samy Mmaee", "Ronaël Pierre-Gabriel", "Kévin Théophile-Catherine", "Mauro Perkovic", "Takuya Ogiwara", "Maxime Bernauer", "Jan Oliveras", "Stefan Ristovski", "Noa Mikic", "Dino Peric"],                                 
        midfielders: ["Arijan Ademi", "Lukas Kacavenda", "Petar Sucic", "Marko Rog", "Tin Miljak", "Luka Stojkovic", "Martin Baturina", "Josip Misic", "Branko Pavic"],
        fronts: ["Bruno Petkovic", "Sandro Kulenovic", "Marko Pjaca", "Mislav Cutuk", "Leon Jakirovic", "Arbër Hoxha", "Juan Córdoba", "Nathanaël Mbuku", "Dario Spikic"],                                                                                  
    },
    {
        name: "FC Bayern München",
        contry: "Germany",
        memberNumber: "37",
        coach: "Vincent Kompany",
        goalkeepers: ["Manuel Neuer", "Sven Ulreich", "Daniel Peretz", "Max Schmitt"],
        defenses: ["Dayot Upamecano", "Eric Dier", "Hiroki Ito", "Sacha Boey", "Josip Stanisic", "Kim Min-Jae", "Alphonso Davies", "Raphaël Guerreiro", "Tarek Buchmann", "Adam Aznou"],                                 
        midfielders: ["Joshua Kimmich", "João Palhinha", "Konrad Laimer", "Leon Goretzka", "Michael Olise", "Aleksandar Pavlovic"],
        fronts: ["Serge Gnabry", "Leroy Sané", "Arijon Ibrahimovic", "Nestory Irankunda", "Jamal Musiala", "Harry Kane", "Kingsley Coman", "Thomas Müller", "Mathys Tel"],                                                                                  
    },
    {
        name: "FC Red Bull Salzburg",
        contry: "Australia",
        memberNumber: "40",
        coach: "Pepijn Lijnders",
        goalkeepers: ["Janis Blaswich", "Valentin Oelz", "Alexander Schlager", "Salko Hamzic"],
        defenses: ["Jannik Schuster", "Aleksa Terzic", "Bryan Okoh", "Oumar Solet", "John Mellberg", "Amar Dedic", "Joane Gadou", "Hendry Blank","Samson Baidoo", "Daouda Guindo","Leandro Morgalla", "Kamil Piatkowski"],                                 
        midfielders: ["Nicolás Capaldo", "Dijon Kameri", "Maurits Kjærgaard", "Takumu Kawamura", "Oliver Lukic", "Oscar Gloukh", "Moussa Yeo","Stefan Bajcetic", "Bobby Clark", "Mamady Diambou", "Mads Bidstrup", "Lucas Gourna-Douath", "Tim Paumgartner"],
        fronts: ["Fernando","Edmund Baidoo", "Adam Daghim","Gaoussou Diakité", "Karim Konaté", "Petar Ratkov", "Dorgeles Nene"],                                                                                  
    },
    {
        name: "Feyenoord",
        contry: "Netherlands",
        memberNumber: "38",
        coach: "Brian Priske",
        goalkeepers: ["Justin Bijlow", "Timon Wellenreuther", "Mannou Berger", "Plamen Andreev"],
        defenses: ["Bart Nieuwkoop", "Gijs Smal", "Facundo González", "Gernot Trauner", "Givairo Read", "Dávid Hancko", "Thomas Beelen", "Quilindschy Hartman", "Hugo Bueno", "Jeyland Mitchell", "Jordan Lotomba", "Jan Plug"],                                 
        midfielders: ["Hwang In-Beom", "Quinten Timber", "Gjivai Zechiël", "Chris-Kévin Nadje", "Ramiz Zerrouki", "Calvin Stengs", "Antoni Milambo"],
        fronts: ["Ayase Ueda", "Luka Ivanusec", "Anis Hadj Moussa", "Ibrahim Osman", "Igor Paixão", "Julián Carranza", "Santiago Giménez"],                                                                                  
    },
    {
        name: "Girona",
        contry: "Spain",
        memberNumber: "35",
        coach: "Delfí Geli",
        goalkeepers: ["Juan Carlos", "Pau López", "Paulo Gazzaniga"],
        defenses: ["Miguel Gutiérrez", "David López", "Alejandro Francés", "Ladislav Krejcí", "Arnau Martínez", "Juanpe", "Daley Blind"],                                 
        midfielders: ["Donny van de Beek", "Oriol Romeu", "Jhon Solís", "Gabriel Misehouy", "Yáser Asprilla", "Yangel Herrera", "Iván Martín", "Raúl Martínez"],
        fronts: ["Cristhian Stuani", "Abel Ruiz", "Bojan Miovski", "Portu", "Viktor Tsyhankov", "Arnaut Danjuma", "Bryan Gil"],                                                                                  
    },
    {
        name: "Internazionale",
        contry: "Italy",
        memberNumber: "36",
        coach: "Zhang Kangyang",
        goalkeepers: ["Yann Sommer", "Josep Martínez", "Raffaele Di Gennaro", "Andrei Radu"],
        defenses: ["Christos Alexiou", "Stefan de Vrij", "Benjamin Pavard", "Yann Bisseck", "Matteo Darmian", "Alessandro Bastoni", "Denzel Dumfries", "Francesco Acerbi", "Carlos Augusto", "Federico Dimarco", "Tomás Palacios"],                                 
        midfielders: ["Piotr Zielinski", "Tajon Buchanan", "Kristjan Asllani", "Nicolò Barella", "Davide Frattesi", "Hakan Çalhanoglu", "Henrikh Mkhitaryan"],
        fronts: ["Marko Arnautovic", "Lautaro Martínez", "Mehdi Taremi", "Marcus Thuram", "Joaquín Correa"],                                                                                  
    },
    {
        name: "Juventus",
        contry: "Italy",
        memberNumber: "36",
        coach: "Thiago Motta",
        goalkeepers: ["Mattia Perin", "Michele Di Gregorio", "Carlo Pinsoglio", "Giovanni Daffara"],
        defenses: ["Bremer", "Danilo", "Andrea Cambiaso", "Nicolò Savona", "Federico Gatti", "Pierre Kalulu", "Juan Cabal", "Jonas Rouhi"],                                 
        midfielders: ["Paul Pogba", "Teun Koopmeiners", "Vasilije Adzic", "Khéphren Thuram", "Timothy Weah", "Manuel Locatelli", "Weston McKennie", "Arthur", "Nicolò Fagioli", "Douglas Luiz"],
        fronts: ["Francisco Conceição", "Kenan Yildiz", "Arkadiusz Milik", "Samuel Mbangula", "Dusan Vlahovic", "Nicolás González", "Lorenzo Anghelè"],                                                                                  
    },
    {
        name: "Lille",
        contry: "France",
        memberNumber: "32",
        coach: "Bruno Génésio",
        goalkeepers: ["Vito Mannone", "Lucas Chevalier", "Marc-Aurèle Caillard"],
        defenses: ["Aïssa Mandi", "Gabriel Gudmundsson", "Akim Zedadka", "Bafodé Diakité", "Tiago Santos", "Ismaily", "Ousmane Touré", "Alexsandro Ribeiro", "Thomas Meunier", "Samuel Umtiti", "Mitchel Bakker", "Rafael Fernandes", "Isaac Cossier"],                                 
        midfielders: ["Nabil Bentaleb", "Angel Gomes", "Ngal'ayel Mukau", "Edon Zhegrova", "Ethan Mbappé", "Lilian Baret", "Hákon Haraldsson", "Rémy Cabella", "Benjamin André", "André Gomes", "Ayyoub Bouaddi"],
        fronts: ["Jonathan David", "Matias Fernandez-Pardo", "Aaron Malouda", "Osame Sahraoui", "Mohamed Bayo", "Younes Lachaab"],                                                                                  
    },
    {
        name: "Liverpool",
        contry: "England",
        memberNumber: "31",
        coach: "Arne Slot",
        goalkeepers: ["Alisson Becker", "Caoimhín Kelleher", "Vítezslav Jaros"],
        defenses: ["Joe Gomez","Ibrahima Konaté", "Andy Robertson", "Jarell Quansah", "Virgil van Dijk", "Kostas Tsimikas", "Trent Alexander-Arnold", "Conor Bradley"],                                 
        midfielders: ["Wataru Endo", "Alexis Mac Allister", "Harvey Elliott", "Tyler Morton", "Dominik Szoboszlai", "Curtis Jones", "Ryan Gravenberch", "Treymaurice Nyoni"],
        fronts: ["Luis Díaz", "Mohamed Salah", "Cody Gakpo", "Darwin Núñez", "Federico Chiesa", "Diogo Jota"],                                                                                  
    },
    {
        name: "Manchester city",
        contry: "England",
        memberNumber: "28",
        coach: "Pep Guardiola",
        goalkeepers: ["Stefan Ortega", "Scott Carson", "Ederson"],
        defenses: ["Kyle Walker", "John Stones", "Josko Gvardiol", "Kaden Braithwaite", "Josh Wilson-Esbrand", "Rúben Dias", "Nathan Aké", "Manuel Akanji", "Rico Lewis"],                                 
        midfielders: ["Mateo Kovacic", "Rodri", "Ilkay Gündogan", "Matheus Nunes", "Oscar Bobb", "Nico O'Reilly", "Jack Grealish", "Kevin De Bruyne", "Bernardo Silva", "Phil Foden", "Jacob Wright", "James McAtee"],
        fronts: ["Erling Haaland", "Savinho", "Jérémy Doku"],                                                                                  
    },
    {
        name: "Milan",
        contry: "Italy",
        memberNumber: "38",
        coach: " Paulo Alexandre Rodrigues Fonseca",
        goalkeepers: ["Mike Maignan", "Marco Sportiello", "Lorenzo Torriani", "Noah Raveyre", "Lapo Nava"],
        defenses: ["Davide Calabria", "Álex Jiménez", "Fikayo Tomori", "Malick Thiaw", "Davide Bartesaghi", "Theo Hernández", "Emerson Royal", "Alessandro Florenzi", "Strahinja Pavlovic", "Matteo Gabbia"],                                 
        midfielders: ["Ismaël Bennacer", "Christian Pulisic", "Kevin Zeroli", "Filippo Terracciano", "Hugo Cuenca", "Ruben Loftus-Cheek", "Tijjani Reijnders", "Youssouf Fofana", "Yunus Musah"],
        fronts: ["Álvaro Morata", "Rafael Leão", "Samuel Chukwueze", "Francesco Camarda", "Luka Jovic", "Noah Okafor", "Chaka Traorè", "Tammy Abraham"],                                                                                  
    },
    {
        name: "Monaco",
        contry: "France",
        memberNumber: "40",
        coach: "Adi Hütter",
        goalkeepers: ["Radoslaw Majecki", "Yann Lienard", "Philipp Köhn"],
        defenses: ["Vanderson", "Thilo Kehrer", "Christian Mawissa","Kassoum Ouattara", "Jordan Teze", "Caio Henrique", "Wilfried Singo","Mohammed Salisu"],                                 
        midfielders: ["Denis Zakaria", "Eliot Matazo", "Maghnes Akliouche", "Takumi Minamino", "Edan Diop", "Mayssam Benama", "Eliesse Ben Seghir", "Aleksandr Golovin", "Lamine Camara", "Krépin Diatta", "Saïmon Bouabré", "Soungoutou Magassa"],
        fronts: ["Folarin Balogun", "Breel Embolo", "George Ilenikhena", "Lucas Michal"],                                                                                  
    },
    {
        name: "PSV Eindhoven",
        contry: "Netherlands",
        memberNumber: "43",
        coach: "Peter Bosz",
        goalkeepers: ["Walter Benítez", "Niek Schiks", "Joël Drommel", "Tijn Smolenaars"],
        defenses: ["Rick Karsdorp", "Ryan Flamingo", "Mauro Júnior", "Emmanuel van de Blaak", "Michael Bresser", "Wessel Kuhn", "Armando Obispo", "Sergiño Dest", "Olivier Boscagli", "Matteo Dams", "Fredrik Oppegård", "Adamo Nagalo"],                                 
        midfielders: ["Malik Tillman", "Jerdy Schouten", "Isaac Babadi", "Ismael Saibari", "Guus Til", "Joey Veerman", "Tygo Land", "Richard Ledezma"],
        fronts: ["Ivan Perisic", "Noa Lang", "Ricardo Pepi", "Hirving Lozano", "Luuk de Jong", "Johan Bakayoko", "Couhaib Driouech", "Jesper Uneken"],                                                                                  
    },
    {
        name: "Paris Saint-Germain",
        contry: "France",
        memberNumber: "39",
        coach: "Luis Enrique Martínez García",
        goalkeepers: ["Gianluigi Donnarumma", "Louis Mouquet", "Matvey Safonov", "Arnau Tenas"],
        defenses: ["Achraf Hakimi", "Marquinhos", "Nuno Mendes", "Milan Skriniar", "Naoufel El Hannach", "Presnel Kimpembe", "Lucas Hernández", "Beraldo", "Yoram Zague", "Willian Pacho"],                                 
        midfielders: ["Fabián Ruiz", "Lee Kang-In", "Warren Zaïre-Emery", "Vitinha", "Senny Mayulu", "João Neves"],
        fronts: ["Gonçalo Ramos", "Marco Asensio", "Randal Kolo Muani", "Ibrahim Mbaye", "Ousmane Dembélé", "Désiré Doué", "Bradley Barcola"],                                                                                  
    },
    {
        name: "RB Leipzig",
        contry: "Germany",
        memberNumber: "35",
        coach: "Marco Rose",
        goalkeepers: ["Péter Gulácsi", "Maarten Vandevoordt", "Leopold Zingerle", "Fernando Dickes"],
        defenses: ["Lutsharel Geertruida", "El Chadaille Bitshiabu", "David Raum", "Benjamin Henrichs", "Willi Orbán", "Lukas Klostermann", "Castello Lukeba"],                                 
        midfielders: ["Eljif Elmas", "Amadou Haidara", "Nicolas Seiwald", "Arthur Vermeeren", "Xaver Schlager", "Kevin Kampl", "Antonio Nusa", "Xavi Simons", "Christoph Baumgartner", "Assan Ouédraogo", "Nuha Jatta", "Viggo Gebel"],
        fronts: ["Yussuf Poulsen", "André Silva", "Loïs Openda", "Benjamin Sesko"],                                                                                  
    },
    {
        name: "Real Madrid",
        contry: "Spain",
        memberNumber: "44",
        coach: "Carlo Ancelotti",
        goalkeepers: ["Thibaut Courtois", "Fran González", "Andrii Lunin", "Sergio Mestre"],
        defenses: ["Dani Carvajal", "David Alaba", "Fran García", "Ferland Mendy", "David Jiménez", "Éder Militão", "Jesús Vallejo", "Antonio Rüdiger", "Jacobo Ramón"],                                 
        midfielders: ["Jude Bellingham", "Federico Valverde", "Aurélien Tchouaméni", "Lucas Vázquez", "Brahim Díaz", "Eduardo Camavinga", "Luka Modric", "Arda Güler", "Dani Ceballos", "Chema Andres"],
        fronts: ["Vinícius Júnior", "Rodrygo", "Kylian Mbappé", "Endrick"],                                                                                  
    },
    {
        name: "Sturm Graz",
        contry: "Australia",
        memberNumber: "38",
        coach: "Christian Ilzer",
        goalkeepers: ["Kjell Scherpen", "Henry Obi", "Matteo Bignetti", "Daniil Khudyakov"],
        defenses: ["Max Johnston", "Alexandar Borkovic", "Jusuf Gazibegovic", "Dimitri Lavalée", "Oliver Sorg", "Emanuel Aiwu", "Gregory Wüthrich", "Emir Karic", "Arjan Malic", "Konstantin Schopp", "Niklas Geyrhofer"],                                 
        midfielders: ["Jacob Peter Hödl", "Malick Yalcouyé", "Lovro Zvonarek", "Tomi Horvat", "Stefan Hierländer", "Jon Gorenc Stankovic", "Otar Kiteishvili", "William Bøving", "Tochi Chukwuani", "Martin Kern"],
        fronts: ["Erencan Yardimci", "Mika Biereth", "Amady Camara", "Manprit Sarkaria", "Seedy Jatta", "Leon Grgic"],                                                                                  
    },
    {
        name: "Slovan Bratislava",
        contry: "Slovakia",
        memberNumber: "33",
        coach: "Vladimír Weiss",
        goalkeepers: ["Andrej Mikolás", "Adam Hrdina", "Martin Trnovsky", "Dominik Takác"],
        defenses: ["Siemen Voet", "Kevin Wimmer", "Jurij Medvedev", "Matús Vojtko", "Guram Kashia", "Kenan Bajric", "Lukás Pauschek", "César Blackman"],                                 
        midfielders: ["Vladimír Weiss", "Tigran Barseghyan", "Nino Marcelli", "Alen Mustafic", "Juraj Kucka", "Danylo Ignatenko", "Marko Tolic", "Maxim Mateás", "Samuel Habodasz", "Artur Gajdos", "Július Szöke", "Kyriakos Savvidis"],
        fronts: ["Martin Misovic", "David Strelec", "Sharani Zuberu", "Elvis Isaac", "Róbert Mak", "Idjessi Metsoko"],                                                                                  
    },
    {
        name: "Shakhtar Donetsk",
        contry: "Ukraine",
        memberNumber: "43",
        coach: "Marino Pusic",
        goalkeepers: ["Tymur Puzankov", "Denys Tvardovskyi", "Dmytro Riznyk", "Kiril Fesiun"],
        defenses: ["Valerii Bondar", "Irakli Azarovi", "Mykola Matviienko", "Maryan Farina", "Pedro Henrique", "Vinícius Tobias", "Yukhym Konoplia"],                                 
        midfielders: ["Bartol Franjic", "Dmytro Kryskiv", "Heorhii Sudakov", "Alaa Ghram", "Artem Bondarenko", "Yehor Nazaryna", "Pedrinho", "Taras Stepanenko", "Marian Shved", "Oleksandr Zubkov", "Anton Hlushchenko", "Viktor Tsukanov", "Marlon Gomes"],
        fronts: ["Lassina Traoré", "Danylo Sikan", "Newerton", "Eguinaldo", "Kevin"],                                                                                  
    },
    {
        name: "Sparta Prague",
        contry: "Czechia",
        memberNumber: "33",
        coach: "Lars Friis",
        goalkeepers: ["Peter Vindahl", "Jakub Surovcík", "Vojtech Vorel"],
        defenses: ["Jakub Uhrincat", "Martin Suchomel", "Mathias Ross", "Asger Sørensen", "Tomás Wiesner", "Matej Rynes", "Martin Vitík", "Dalibor Vecerka", "Imanol García de Albéniz", "Ángelo Preciado", "Filip Panák", "Jaroslav Zeleny", "Elias Cobbaut"],                                 
        midfielders: ["Markus Solbakken", "David Pavelka", "Veljko Birmancevic", "Qazim Laçi", "Lukás Haraslín", "Roman Mokrovics", "Kaan Kairinen", "Krystof Danek", "Lukás Sadílek", "Jakub Pesek", "Ermal Krasniqi"],
        fronts: ["Vojtech Hranos", "Albion Rrahmani", "Radek Siler", "Victor Olatunji", "Indrit Tuci", "Daniel Rus"],                                                                                  
    },
    {
        name: "Sporting de Portugal",
        contry: "Portugal",
        memberNumber: "37",
        coach: "Rúben Filipe Marques Diogo Amorim",
        goalkeepers: ["Franco Israel", "Diego Callai", "Francisco Silva", "Vladan Kovacevic", "Diogo Pinto"],
        defenses: ["Matheus Reis", "Zeno Debast", "Gonçalo Inácio", "Ricardo Esgaio", "Miguel Alves", "Jeremiah St. Juste", "Iván Fresneda", "Ousmane Diomande", "Bruno Ramos", "Eduardo Quaresma"],                                 
        midfielders: ["Hidemasa Morita", "Nuno Santos", "Geny Catamo", "Morten Hjulmand", "Geovany Quenda", "Pote", "Maximiliano Araújo", "Daniel Bragança", "João Simões", "Kauã Oliveira"],
        fronts: ["Viktor Gyökeres", "Trincão", "Mauro Couto", "Rafael Nel", "Marcus Edwards", "Conrad Harder", "Luís Gomes", "Afonso Moreira"],                                                                                  
    },
    {
        name: "VfB Stuttgart",
        contry: "Germany",
        memberNumber: "34",
        coach: "Sebastian Hoeneß",
        goalkeepers: ["Fabian Bredlow", "Alexander Nübel", "Stefan Drljaca", "Dennis Seimen"],
        defenses: ["Ameen Al Dakhil", "Josha Vagnoman", "Frans Krätzig", "Leonidas Stergiou", "Jeff Chabot", "Anrie Chase", "Ramon Hendriks", "Maximilian Mittelstädt", "Pascal Stenzel", "Dan-Axel Zagadou", "Anthony Rouault"],                                 
        midfielders: ["Yannik Keitel", "Enzo Millot", "Chris Führich", "Christopher Olivier", "Luca Raimund", "Angelo Stiller", "Atakan Karazor", "Nikolas Nartey", "Fabian Rieder"],
        fronts: ["Ermedin Demirovic", "Nick Woltemade", "Jamie Leweling", "Thomas Kastanaras", "El Bilal Touré", "Justin Diehl", "Wahid Faghir", "Deniz Undav"],                                                                                  
    },
    {
        name: "Young Boys",
        contry: "Swiss",
        memberNumber: "32",
        coach: "Joël Magnin",
        goalkeepers: ["Ardian Bajrami", "Marvin Keller", "David von Ballmoos", "Dario Marzino"],
        defenses: ["Jaouen Hadjam", "Anel Husic", "Mohamed Ali Camara", "Abdu Conté", "Zachary Athekame", "Sadin Crnovrsanin", "Tanguy Zoukrou", "Patric Pfeiffer", "Saidy Janko", "Loris Benito", "Lewin Blum", "Mats Seiler"],                                 
        midfielders: ["Filip Ugrinic", "Kastriot Imeri", "Cheikh Niasse", "Darian Males", "Lukasz Lakomy", "Miguel Chaiwa", "Sandro Lauper"],
        fronts: ["Cedric Itten", "Meschack Elia", "Facinet Conte", "Joël Monteiro", "Ebrima Colley", "Alan Virginius", "Silvere Ganvoula"],                                                                                  
    }
]

export default Equipos;